# Bitfinex Exchange Configuration
# This file contains exchange-specific settings and REST API configuration endpoints

endpoints:
  ws_public: "wss://api-pub.bitfinex.com/ws/2"
  ws_auth: "wss://api.bitfinex.com/ws/2"
  rest_public: "https://api-pub.bitfinex.com/v2"

limits:
  ws_connections_per_minute: 20
  ws_max_subscriptions: 30
  rest_rate_limit: 90  # requests per minute

defaults:
  book:
    prec: "P0"
    freq: "F0"
    len: "25"
  candles:
    timeframe: "1m"

normalization:
  pair_format: "base-quote"  # Internal format
  uppercase: true

rest_config_endpoints:
  - endpoint: "pub:list:pair:exchange"
    cache_duration: 3600  # 1 hour
    file: "list_pair_exchange.json"
  - endpoint: "pub:list:pair:margin"
    cache_duration: 3600
    file: "list_pair_margin.json"
  - endpoint: "pub:list:pair:futures"
    cache_duration: 3600
    file: "list_pair_futures.json"
  - endpoint: "pub:list:currency"
    cache_duration: 86400  # 24 hours
    file: "list_currency_margin.json"
  - endpoint: "pub:map:currency:label"
    cache_duration: 86400
    file: "map_currency_label.json"
  - endpoint: "pub:map:currency:sym"
    cache_duration: 86400
    file: "map_currency_sym.json"