# Default Bitfinex exchange configuration
websocket:
  url: "wss://api-pub.bitfinex.com/ws/2"
  reconnect_interval: "5s"
  heartbeat_timeout: "45s"
  ping_interval: "30s"
  max_connections: 5
  connection_timeout: "10s"

  # Bitfinex configuration flags (合算値: 537100288)
  # TIMESTAMP(32768) + SEQ_ALL(65536) + OB_CHECKSUM(131072) + BULK_UPDATES(536870912)
  conf_flags: 537100288

# Symbols to subscribe to
symbols:
  - "tBTCUSD"
  - "tETHUSD"

# Channel subscriptions configuration
channels:
  ticker:
    enabled: true
    sampling_rate: "1s" # Reduce from real-time to 1Hz

  trades:
    enabled: true
    msg_type: "tu" # Only save "trade updated" messages to avoid duplicates

  books:
    enabled: true
    precision: "P0" # P0, P1, P2, P3, P4
    frequency: "F0" # F0 (real-time), F1 (2 seconds)
    length: 25 # 1, 25, 100, 250

  raw_books:
    enabled: true
    precision: "R0" # Raw order books
    frequency: "F0"
    length: 25
