# This file is managing state of last updates or selected items for various data points of metadata or config of exchanges.
# It could be auto updated by the application or selected manually by the user.
# It is also used to avoid redundant fetching of data that rarely changes.
# For the UTC timestamps are in ISO 8601 format.
exchanges:
    bitfinex:
        pub:fees: "2025-09-29T16:46:26Z"
        pub:info:pair: "2025-09-29T16:46:22Z"
        pub:info:pair:futures: "2025-09-29T16:46:23Z"
        pub:info:tx:status: "2025-09-29T16:46:28Z"
        pub:list:competitions: "2025-09-29T17:30:59Z"
        pub:list:currency:margin: "2025-09-29T16:46:27Z"
        pub:list:pair:exchange: "2025-09-29T16:46:21Z"
        pub:list:pair:futures: "2025-09-29T16:46:22Z"
        pub:list:pair:margin: "2025-09-29T16:46:21Z"
        pub:map:currency:explorer: "2025-09-29T17:30:57Z"
        pub:map:currency:label: "2025-09-29T17:30:56Z"
        pub:map:currency:pool: "2025-09-29T17:30:58Z"
        pub:map:currency:sym: "2025-09-29T16:46:25Z"
        pub:map:currency:tx:fee: "2025-09-29T16:46:27Z"
        pub:map:currency:undl: "2025-09-29T17:31:00Z"
        pub:map:currency:unit: "2025-09-29T17:30:57Z"
        pub:spec:margin: "2025-09-29T16:46:24Z"
