exchanges:
    bitfinex:
        ws:
            connections:
                - id: conn_1
                  status: connected
                  connected_at: 2025-09-30T11:46:50.765588+02:00
                  subscriptions:
                    - channel: ticker
                      symbol: tBTCUSD
                      chanId: 12345
            ui_state:
                active_tab: ticker
                selected_symbols:
                    - tBTCUSD
                    - tETHUSD
                connection_flags:
                    checksum: true
                    bulk: false
                    timestamp: true
                    sequence: false
                channel_states:
                    books:
                        enabled: false
                        frequency: F0
                        length: "25"
                        precision: P0
                        selected_symbols: []
                    candles:
                        enabled: false
                        selected_symbols: []
                        timeframe: 1m
                    status:
                        enabled: false
                        status_type: derivatives
                    ticker:
                        enabled: true
                        selected_symbols:
                            - tADABTC
                    trades:
                        enabled: false
                        selected_symbols: []
        rest_config_cache:
            last_updated:
                pub:list:currency: 2025-10-01T20:04:13.919496+02:00
                pub:list:pair:exchange: 2025-10-01T20:04:13.924917+02:00
                pub:list:pair:futures: 2025-10-01T20:04:13.922113+02:00
                pub:list:pair:margin: 2025-10-01T20:04:13.951276+02:00
                pub:map:currency:label: 2025-10-01T20:04:13.922109+02:00
                pub:map:currency:sym: 2025-10-01T20:04:13.923779+02:00
            next_update:
                pub:list:currency: 2025-10-02T20:04:13.919496+02:00
                pub:list:pair:exchange: 2025-10-01T21:04:13.924917+02:00
                pub:list:pair:futures: 2025-10-01T21:04:13.922113+02:00
                pub:list:pair:margin: 2025-10-01T21:04:13.951276+02:00
                pub:map:currency:label: 2025-10-02T20:04:13.922109+02:00
                pub:map:currency:sym: 2025-10-02T20:04:13.923779+02:00
